# Пример строковой переменной
name = "Константа"
# Пример числовой переменной
value = 42
# Пример массива
array = [1, 2, 3, 4]
# Далее приведены несколько словарей:
# person - словарь с вложенным словарем
#constants - словарь с константами
# calculations - словарь с вычислениями константых выражений

[person]
name = "Иван"
age = 30

[person.address]
street = "ул. Ленина, 5"
city = "Москва"

[constants]
a = 5.2
b = 3.5
c = 14

[calculations]
sum = "#{a + 5}"
sub = "#{b - 2}"
mul = "#{a * b}"
div = "#{c / b}"
min = "#{min(a, min(b, c))}"